PREDICATE_SUBJECT = 'is_subject_of'
PREDICATE_OBJECT = 'is_object_of'

PAGINATION = 20

KNOWLEDGE_SET_ONTOLOGY = 'ONTOLOGY'
KNOWLEDGE_SET_INSTANCES = 'INSTANCES'
KNOWLEDGE_SET_CHOICES = [
    (KNOWLEDGE_SET_ONTOLOGY, 'Ontology'),
    (KNOWLEDGE_SET_INSTANCES, 'Instances'),
]

TIME_SCHEDULE_NOW = 'NOW'
TIME_SCHEDULE_SCHEDULED = 'SCHEDULED'
TIME_SCHEDULE_CHOICES = [
    (TIME_SCHEDULE_NOW, 'Now'),
    (TIME_SCHEDULE_SCHEDULED, 'Scheduled'),
]