# Generated by Django 4.1 on 2023-08-25 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=1024, null=True)),
                ('target', models.UUIDField(blank=True, null=True)),
                ('uri', models.CharField(blank=True, max_length=1024, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisation_logs', to='organisation.organisation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
