# Generated by Django 4.1 on 2022-11-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oconcept',
            name='tag_groups',
        ),
        migrations.RemoveField(
            model_name='oinstance',
            name='tag_groups',
        ),
        migrations.RemoveField(
            model_name='omodel',
            name='tag_groups',
        ),
        migrations.RemoveField(
            model_name='opredicate',
            name='tag_groups',
        ),
        migrations.RemoveField(
            model_name='orelation',
            name='tag_groups',
        ),
        migrations.RemoveField(
            model_name='oreport',
            name='tag_groups',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='tag_groups',
        ),
    ]
