# Generated by Django 4.1 on 2023-08-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oconcept',
            name='native',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opredicate',
            name='native',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orelation',
            name='native',
            field=models.BooleanField(default=False),
        ),
    ]
