# Generated by Django 4.1 on 2023-04-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oslot',
            name='order',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
