# Generated by Django 4.1 on 2023-08-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0002_oconcept_native_opredicate_native_orelation_native'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opredicate',
            name='native',
        ),
        migrations.AddField(
            model_name='oslot',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
