# Generated by Django 4.1 on 2023-04-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0002_oslot_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oslot',
            name='order',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
