from .task import TaskDeleteTestCase
from .task import TaskUpdateTestCase
from .task import TaskDetailTestCase
from .task import TaskCreateTestCase
from .task import TaskListTestCase
from .profile import ProfileDeleteTestCase
from .profile import ProfileUpdateTestCase
from .profile import ProfileDetailTestCase
from .profile import ProfileCreateTestCase
from .profile import ProfileListTestCase
from .organisation import OrganisationDeleteTestCase
from .organisation import OrganisationUpdateTestCase
from .organisation import OrganisationDetailTestCase
from .organisation import OrganisationCreateTestCase
from .organisation import OrganisationListTestCase
