from .o_slot_delete_test import OSlotDeleteTestCase
from .o_slot_update_test import OSlotUpdateTestCase
from .o_slot_detail_test import OSlotDetailTestCase
from .o_slot_create_test import OSlotCreateTestCase
from .o_slot_list_test import OSlotListTestCase
