from .o_instance_delete import OInstanceDeleteView
from .o_instance_update import OInstanceUpdateView
from .o_instance_detail import OInstanceDetailView
from .o_instance_create import OInstanceCreateView
from .o_instance_list import OInstanceListView
