from .o_report import OReportDeleteView
from .o_report import OReportUpdateView
from .o_report import OReportDetailView
from .o_report import OReportCreateView
from .o_report import OReportListView
from .o_instance import OInstanceDeleteView
from .o_instance import OInstanceUpdateView
from .o_instance import OInstanceDetailView
from .o_instance import OInstanceCreateView
from .o_instance import OInstanceListView
from .o_predicate import OPredicateDeleteView
from .o_predicate import OPredicateUpdateView
from .o_predicate import OPredicateDetailView
from .o_predicate import OPredicateCreateView
from .o_predicate import OPredicateListView
from .o_relation import ORelationDeleteView
from .o_relation import ORelationUpdateView
from .o_relation import ORelationDetailView
from .o_relation import ORelationCreateView
from .o_relation import ORelationListView
from .o_concept import OConceptDeleteView
from .o_concept import OConceptUpdateView
from .o_concept import OConceptDetailView
from .o_concept import OConceptCreateView
from .o_concept import OConceptListView
from .o_model import OModelDeleteView
from .o_model import OModelUpdateView
from .o_model import OModelDetailView
from .o_model import OModelCreateView
from .o_model import OModelListView
from .repository import RepositoryDeleteView
from .repository import RepositoryUpdateView
from .repository import RepositoryDetailView
from .repository import RepositoryCreateView
from .repository import RepositoryListView

from .o_model import OModelReportView