from .o_report_delete_test import OReportDeleteTestCase
from .o_report_update_test import OReportUpdateTestCase
from .o_report_detail_test import OReportDetailTestCase
from .o_report_create_test import OReportCreateTestCase
from .o_report_list_test import OReportListTestCase
