# Generated by Django 4.1 on 2023-04-06 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_group_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_group_deleted', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_group_modified', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisation_security_groups', to='organisation.organisation')),
                ('profiles', models.ManyToManyField(related_name='security_groups', to='organisation.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LIST', 'List'), ('CREATE', 'Create'), ('VIEW', 'View'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('RUN', 'Run'), ('IMPORT', 'Import'), ('EXPORT', 'Export')], default='VIEW', max_length=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_type', models.CharField(choices=[('ORGA', 'Organisation'), ('PROF', 'Profile'), ('TASK', 'Task'), ('SECG', 'Security Group'), ('PERM', 'Permission'), ('REPO', 'Repository'), ('MODE', 'Model'), ('CONC', 'Concept'), ('RELA', 'Relation'), ('PRED', 'Predicate'), ('INST', 'Instance'), ('REPT', 'Report'), ('TAGG', 'Tag Group'), ('TAG', 'Tag'), ('CONF', 'Configuration'), ('LOG', 'Log')], max_length=4)),
                ('object_identifier', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permission_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permission_deleted', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permission_modified', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisation_permissions', to='organisation.organisation')),
                ('security_groups', models.ManyToManyField(related_name='permissions', to='authorization.securitygroup')),
            ],
        ),
    ]
