# Generated by Django 4.1 on 2023-04-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='object_type',
            field=models.CharField(choices=[('ORGA', 'Organisation'), ('POST', 'Post'), ('PROF', 'Profile'), ('TASK', 'Task'), ('SECG', 'Security Group'), ('PERM', 'Permission'), ('REPO', 'Repository'), ('MODE', 'Model'), ('CONC', 'Concept'), ('RELA', 'Relation'), ('PRED', 'Predicate'), ('INST', 'Instance'), ('REPT', 'Report'), ('TAGG', 'Tag Group'), ('TAG', 'Tag'), ('CONF', 'Configuration'), ('LOG', 'Log')], max_length=4),
        ),
    ]
