# Generated by Django 4.1 on 2023-04-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
