PREDICATE_SUBJECT = 'is_subject_of'
PREDICATE_OBJECT = 'is_object_of'

PAGINATION = 20

KNOWLEDGE_SET_ONTOLOGY = 'ONTOLOGY'
KNOWLEDGE_SET_INSTANCES = 'INSTANCES'
KNOWLEDGE_SET_CHOICES = [
    (KNOWLEDGE_SET_ONTOLOGY, 'Ontology'),
    (KNOWLEDGE_SET_INSTANCES, 'Instances'),
]

